import os
import torch
import matplotlib
matplotlib.use('Agg')
from utils.utils import load_config
from data.data_loader import get_dataloader
from models.forward_diffusion import DiscreteGraphDiffusion
from models.backward_diffusion import BackwardDiffusionModel
from models.sequence_generator import SequenceGenerator
from models.heuristic_evaluator import ValidityHeuristicEvaluator
from train import plot_full_diffusion_process

def main():
    config = load_config('config.yaml')
    device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
    
    out_cfg = config.get('output', {})
    base_dir = out_cfg.get('base_dir', 'output')
    ckpt_dir = os.path.join(base_dir, out_cfg.get('checkpoints_dir', 'checkpoints'))
    img_dir = os.path.join(base_dir, out_cfg.get('images_dir', 'corrupted_disjoint_trees'))
    os.makedirs(img_dir, exist_ok=True)
    
    # Load dataset
    _, val_loader = get_dataloader(config, world_size=1, rank=0)
    
    # Initialize models
    forward_diffusion = DiscreteGraphDiffusion(config=config)
    diff_model = BackwardDiffusionModel(config=config).to(device)
    gen_model = SequenceGenerator(config=config).to(device)
    
    # Load epoch 75 checkpoints
    epoch = 75
    diff_ckpt = os.path.join(ckpt_dir, f"diff_epoch_{epoch}.pth")
    gen_ckpt = os.path.join(ckpt_dir, f"gen_epoch_{epoch}.pth")
    
    if os.path.exists(diff_ckpt) and os.path.exists(gen_ckpt):
        # Using strict=False in case of module. wrapper from DDP
        diff_state = torch.load(diff_ckpt, map_location=device)
        gen_state = torch.load(gen_ckpt, map_location=device)
        
        # Remove 'module.' prefix if it exists
        diff_state = {k.replace('module.', ''): v for k, v in diff_state.items()}
        gen_state = {k.replace('module.', ''): v for k, v in gen_state.items()}
        
        diff_model.load_state_dict(diff_state)
        gen_model.load_state_dict(gen_state)
        print(f"Loaded checkpoints for epoch {epoch}")
    else:
        print(f"Checkpoints for epoch {epoch} not found!")
        return

    diff_model.eval()
    gen_model.eval()
    
    with torch.no_grad():
        for batch_idx, batch in enumerate(val_loader):
            # Just take the first validation batch
            if batch is None:
                continue
                
            x = batch['x'].to(device)
            true_edge_index = batch['edge_index'].to(device)
            batch_assignment = batch['batch'].to(device)
            
            # Forward diffusion sample
            t_batch = torch.randint(0, forward_diffusion.num_timesteps, (1,), device=device)
            noisy_edges, _ = forward_diffusion.forward_sample(true_edge_index, t_batch)
            
            # Context for sequence generator
            t1_context = torch.zeros(len(x), 128, device=device) # Dummy or get actual from backward diff
            t2_context = torch.zeros(len(x), 128, device=device)
            
            save_path_full = os.path.join(img_dir, f"epoch_{epoch}_full_diffusion.png")
            
            # Extract single graph for the forward corruption visualization
            mask = (batch_assignment == 0)
            node_indices = torch.where(mask)[0]
            if len(node_indices) > 0:
                x_single = x[mask]
                edge_mask_orig = mask[true_edge_index[0]] & mask[true_edge_index[1]]
                true_edges_single = true_edge_index[:, edge_mask_orig]
                mapping = torch.zeros(x.shape[0], dtype=torch.long, device=device)
                mapping[node_indices] = torch.arange(len(node_indices), device=device)
                true_edges_single = mapping[true_edges_single]
                
                # In train.py, t1_context and t2_context are generated by diff_model.
                # Let's run a dummy diff_model forward pass to get actual context
                t = torch.randint(0, 100, (len(x),), device=device)
                # Need candidate edges for diff_model... let's just create random candidates
                import itertools
                u_nodes = torch.where(mask)[0].cpu().tolist()
                candidates = torch.tensor(list(itertools.combinations(u_nodes, 2)), device=device).T
                if candidates.numel() == 0:
                    candidates = torch.zeros((2, 0), dtype=torch.long, device=device)
                    
                _, context = diff_model(x, noisy_edges, batch_assignment, t, candidates)
                # Sequence generator expects context
                t1_context = context
                t2_context = context
                
                plot_full_diffusion_process(
                    x_single, true_edges_single, forward_diffusion, gen_model, 
                    t1_context, t2_context, save_path_full
                )
                print(f"Generated {save_path_full}")
                break # Only need one image

if __name__ == '__main__':
    main()
